package com.example.fitfusion.Quotes

object Quotesfile {
    val quotes = listOf(
        "The greatest wealth is health.",
        "To enjoy the glow of good health, you must exercise.",
        "Take care of your body. It’s the only place you have to live.",
        "A fit body, a calm mind, a house full of love. These things cannot be bought – they must be earned.",
        "Health is not valued till sickness comes.",
        "Health is the crown on the well person’s head that only the ill person can see.",
        "Your body deserves the best.",
        "Healthy does NOT mean starving yourself EVER. Healthy means eating the right food in the right amount.",
        "Exercise is king. Nutrition is queen. Put them together and you've got a kingdom.",
        "The first wealth is health.",
        "To keep the body in good health is a duty, otherwise we shall not be able to keep our mind strong and clear.",
        "It is health that is real wealth and not pieces of gold and silver.",
        "An apple a day keeps the doctor away.",
        "Health is the thing that makes you feel that now is the best time of the year.",
        "Your body hears everything your mind says.",
        "You can’t enjoy wealth if you’re not in good health.",
        "A healthy outside starts from the inside.",
        "Health and cheerfulness naturally beget each other.",
        "The groundwork of all happiness is good health.",
        "Happiness is the highest form of health.",
        "If you don’t take care of your body, where are you going to live?",
        "Good health is not something we can buy. However, it can be an extremely valuable savings account.",
        "The human body is the best picture of the human soul.",
        "Health requires healthy food.",
        "Eat to live, not live to eat.",
        "Those who do not find time for exercise will have to find time for illness.",
        "Take care of your body. It’s the only place you have to live.",
        "The body achieves what the mind believes.",
        "The only bad workout is the one that didn’t happen.",
        "The reason I exercise is for the quality of life I enjoy.",
        "Fitness is not about being better than someone else. It’s about being better than you used to be.",
        "Strength does not come from physical capacity. It comes from an indomitable will.",
        "Your health account, your bank account, they’re the same thing. The more you put in, the more you can take out.",
        "Physical fitness is the first requisite of happiness.",
        "The purpose of training is to tighten up the slack, toughen the body, and polish the spirit.",
        "To keep the body in good health is a duty… otherwise we shall not be able to keep our mind strong and clear.",
        "When you feel like quitting think about why you started.",
        "Movement is a medicine for creating change in a person’s physical, emotional, and mental states.",
        "If it doesn’t challenge you, it doesn’t change you.",
        "Your body can stand almost anything. It’s your mind that you have to convince.",
        "Success is what comes after you stop making excuses.",
        "If you think lifting is dangerous, try being weak. Being weak is dangerous.",
        "Fitness is like a relationship. You can’t cheat and expect it to work.",
        "The only way to keep your health is to eat what you don’t want, drink what you don’t like, and do what you’d rather not.",
        "The reason I exercise is for the quality of life I enjoy.",
        "The pain you feel today will be the strength you feel tomorrow.",
        "If you’re tired of starting over, stop giving up.",
        "What seems impossible today will one day become your warm-up.",
        "Sweat is fat crying.",
        "Fitness is not about being better than someone else. It’s about being better than you used to be.",
        "Your body can do it. It’s time to convince your mind.",
        "Push yourself because no one else is going to do it for you.",
        "Success starts with self-discipline.",
        "Good things come to those who sweat.",
        "Fitness is not a destination, it’s a way of life.",
        "Don’t stop when you’re tired. Stop when you’re done.",
        "You are one workout away from a good mood.",
        "The only bad workout is the one that didn’t happen.",
        "Eat clean, stay fit, and have a burger to stay sane.",
        "The difference between wanting and achieving is discipline.",
        "Exercise is labor without weariness.",
        "Reading is to the mind what exercise is to the body.",
        "The body achieves what the mind believes.",
        "To enjoy the glow of good health, you must exercise.",
        "When you feel like quitting think about why you started.",
        "Strength does not come from physical capacity. It comes from an indomitable will.",
        "Exercise is a celebration of what your body can do. Not a punishment for what you ate.",
        "The best project you will ever work on is you.",
        "Health is a state of body. Wellness is a state of being.",
        "Take care of your body. It’s the only place you have to live.",
        "Healthy isn’t a goal. It’s a way of living.",
        "Invest in your health now, or invest in more medicine later.",
        "A healthy lifestyle is something we refine over time, not overnight.",
        "It’s not about being the best. It’s about being better than you were yesterday.",
        "The doctor of the future will give no medicine, but will instruct his patient in the care of the human frame, in diet, and in the cause and prevention of disease.",
        "Time and health are two precious assets that we don’t recognize and appreciate until they have been depleted.",
        "Health is like money, we never have a true idea of its value until we lose it.",
        "The food you eat can either be the safest and most powerful form of medicine or the slowest form of poison.",
        "The difference between the impossible and the possible lies in a person’s determination.",
        "It always seems impossible until it’s done.",
        "Health is not about the weight you lose, but about the life you gain.",
        "Your health is an investment, not an expense.",
        "Take care of your body, it’s the only place you have to live.",
        "True enjoyment comes from activity of the mind and exercise of the body; the two are ever united.",
        "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.",
        "The groundwork for all happiness is good health.",
        "A good laugh and a long sleep are the best cures in the doctor’s book.",
        "Happiness is nothing more than good health and a bad memory.",
        "Health is the vital principle of bliss, and exercise, of health.",
        "A healthy outside starts from the inside.",
        "Health and cheerfulness naturally beget each other.",
        "Healthy does NOT mean starving yourself EVER. Healthy means eating the right food in the right amount.",
        "The greatest of follies is to sacrifice health for any other kind of happiness.",
        "The groundwork of all happiness is health.",
        "The power of love to change bodies is legendary, built into folklore, common sense, and everyday experience. Love moves the flesh, it pushes matter around. Throughout history, “tender loving care” has uniformly been recognized as a valuable element in healing.",
        "Life expectancy would grow by leaps and bounds if green vegetables smelled as good as bacon.",
        "The best and most efficient pharmacy is within your own system.",
        "Early to bed and early to rise, makes a man healthy, wealthy, and wise.",
        "Health is the thing that makes you feel that now is the best time of the year."
    )
}